export const SPECIALTIES = [
  "Cardiologia",
  "Dermatologia",
  "Endocrinologia",
  "Gastroenterologia",
  "Ginecologia",
  "Geriatria",
  "Hematologia",
  "Infectologia",
  "Neurologia",
  "Oftalmologia",
  "Oncologia",
  "Ortopedia",
  "Otorrinolaringologia",
  "Pediatria",
  "Pneumologia",
  "Psiquiatria",
  "Reumatologia",
  "Urologia",
  "Clínico Geral",
  "Enfermagem",
  "Nutrição",
  "Psicologia",
  "Fisioterapia",
  "Fonoaudiologia",
];
