"""create_users_table

Revision ID: f1dfe9ac08cb
Revises: 002_patients_convenios
Create Date: 2026-04-19 21:23:03.711543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1dfe9ac08cb'
down_revision: Union[str, None] = '002_patients_convenios'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('appointment_types', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.add_column('availability_blocks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('availability_blocks', 'recurring',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('convenios', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_patients_document', table_name='patients')
    op.drop_index('ix_patients_phone', table_name='patients')
    op.alter_column('professionals', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('provider_routes', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('scheduling_settings', 'weekday_opening',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_server_default=sa.text("'08:00:00'::time without time zone"))
    op.alter_column('scheduling_settings', 'weekday_closing',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_server_default=sa.text("'17:00:00'::time without time zone"))
    op.alter_column('scheduling_settings', 'saturday_opening',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_server_default=sa.text("'08:00:00'::time without time zone"))
    op.alter_column('scheduling_settings', 'saturday_closing',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_server_default=sa.text("'12:00:00'::time without time zone"))
    op.alter_column('scheduling_settings', 'sunday_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('scheduling_settings', 'holidays_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('scheduling_settings', 'buffer_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scheduling_settings', 'max_advance_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('60'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduling_settings', 'max_advance_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('60'))
    op.alter_column('scheduling_settings', 'buffer_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scheduling_settings', 'holidays_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('scheduling_settings', 'sunday_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('scheduling_settings', 'saturday_closing',
               existing_type=postgresql.TIME(),
               nullable=False,
               existing_server_default=sa.text("'12:00:00'::time without time zone"))
    op.alter_column('scheduling_settings', 'saturday_opening',
               existing_type=postgresql.TIME(),
               nullable=False,
               existing_server_default=sa.text("'08:00:00'::time without time zone"))
    op.alter_column('scheduling_settings', 'weekday_closing',
               existing_type=postgresql.TIME(),
               nullable=False,
               existing_server_default=sa.text("'17:00:00'::time without time zone"))
    op.alter_column('scheduling_settings', 'weekday_opening',
               existing_type=postgresql.TIME(),
               nullable=False,
               existing_server_default=sa.text("'08:00:00'::time without time zone"))
    op.alter_column('provider_routes', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('professionals', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('ix_patients_phone', 'patients', ['phone'], unique=False)
    op.create_index('ix_patients_document', 'patients', ['document'], unique=False)
    op.alter_column('convenios', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('availability_blocks', 'recurring',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.drop_column('availability_blocks', 'updated_at')
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.alter_column('appointment_types', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
